inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rock: defaults.yml

AllCops:
  TargetRubyVersion: "2.5"

Style/MultilineMemoization:
    EnforcedStyle: braces

Style/StderrPuts:
    Enabled: false

Naming/PredicateName:
    Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/yard-syskit.rb'
    - 'test/roby_app/app/models/compositions/reload_ruby_task-1.rb'
    - 'test/roby_app/app/models/compositions/reload_ruby_task-2.rb'